# Generated by Django 5.2.17 on 2026-09-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical Skill'), ('soft', 'Soft Skill'), ('language', 'Language')], default='technical', max_length=50),
        ),
    ]
